return {
    "Prize - Plushie: Freddy Plush",
    "Prize - Plushie: Bonnie Plush",
    "Prize - Plushie: Chica Plush",
    "Prize - Plushie: Foxy Plush",
    "Prize - Plushie: Golden Freddy Plush",
    "Prize - Plushie: Springtrap Plush",
    "Prize - Plushie: Toy Freddy Plush",
    "Prize - Plushie: Toy Bonnie Plush",
    "Prize - Plushie: Toy Chica Plush",
    "Prize - Plushie: Mangle Plush",
    "Prize - Plushie: BB Plush",
    "Prize - Plushie: JJ Plush",
    "Prize - Plushie: Puppet Plush",
    "Prize - Plushie: Plushtrap Plush",
    "Prize - Plushie: Nightmare Freddy Plush",
    "Prize - Plushie: Nightmare Bonnie Plush",
    "Prize - Plushie: Nightmare Chica Plush",
    "Prize - Plushie: Nightmare Fredbear Plush",
    "Prize - Plushie: Nightmarionne Plush",
    "Prize - Plushie: Helpy Plush",
    "Prize - Plushie: Plushbaby",
    "Prize - Plushie: Plushbaby (Scrap Baby ver.)",
    "Prize - Plushie: Funtime Foxy",
    "Prize - Plushie: Funtime Freddy",
    "Prize - Action Figure: Freddy Action Figure",
    "Prize - Action Figure: Bonnie Action Figure",
    "Prize - Action Figure: Chica Action Figure",
    "Prize - Action Figure: Foxy Action Figure",
    "Prize - Action Figure: Golden Freddy Action Figure",
    "Prize - Action Figure: Springtrap Action Figure",
    "Prize - Action Figure: Toy Freddy Action Figure",
    "Prize - Action Figure: Toy Bonnie Action Figure",
    "Prize - Action Figure: Toy Chica Action Figure",
    "Prize - Action Figure: Mangle Action Figure",
    "Prize - Action Figure: Puppet Action Figure",
    "Prize - Action Figure: Circus Baby Action Figure",
    "Prize - Action Figure: Ballora Action Figure",
    "Prize - Action Figure: Funtime Freddy Action Figure",
    "Prize - Action Figure: Funtime Foxy Action Figure",
    "Prize - Action Figure: Ennard Action Figure",
    "Prize - Action Figure: Balloon Boy Action Figure",
    "Prize - Action Figure: Plushtrap Action Figure",
    "Prize - Action Figure: Nightmarionne Action Figure",
    "Prize - Action Figure: Nightmare Fredbear Action Figure",
    "Prize - Action Figure: Bon-Bon Action Figure",
    "Prize - Other: Exotic Butters",
    "Prize - Other: Mr. Cupcake",
    "Prize - Other: Pizza Slice",
    "Prize - Other: Faz Soda",
    "Prize - Other: Bon-Bon Hand Puppet",
    "Prize - Other: Mini Music Box",
    "Prize - Other: Candy Bucket",
    "Prize - Other: Freddy Bobblehead",
    "Prize - Other: Bonnie Bobblehead",
    "Prize - Other: Chica Bobblehead",
    "Prize - Other: Foxy Bobblehead",
    "Prize - Other: Nightmarionne Bobblehead",
    "Prize - Other: Mystery Box",
    "Prize - Other: Prize Counter Poster",
    "Prize - Food/Drink: Disappointment Chips",
    "Prize - Food/Drink: El Chip's Tortilla Chips Bold and Spicy",
    "Prize - Food/Drink: Meat Bites XL",
    "Prize - Food/Drink: Bonnie Bites",
    "Prize - Food/Drink: Allergy Friendly Mixed Nuts",
    "Prize - Food/Drink: Meat Bites",
    "Prize - Food/Drink: Stick of Butter",
    "Prize - Food/Drink: Pirate Plunderbar",
    "Prize - Food/Drink: Foxy Cove Cooler",
    "Prize - Food/Drink: Butter for One",
    "Prize - Food/Drink: Freddy Fudgebar",
    "Prize - Food/Drink: Exotic Beverage",
    "Prize - Food/Drink: Sodaroni",
    "Prize - Food/Drink: Chica Chug",
    "Prize - Food/Drink: El Chip's Tortilla Chips",
    "Prize - Food/Drink: Fazbar",
    "Prize - Food/Drink: Lemon Chica Bar",
    "Prize - Food/Drink: Slice of Cake",
    "Prize - Toy: Cupcake",
    "Prize - Toy: Toy phone",
    "Prize - Toy: Toy Catterpillar",
    "Prize - Toy: Toy Robot",
}
