import json
from pathlib import Path

data = json.loads(Path("ue4ss_mod/FNAFHWArchipelago/locations.json").read_text(encoding="utf-8"))

lines = [
    "-- Generated by scripts/generate_locations_json.py",
    "-- Do not edit manually.",
    "local locations_data = {}",
    "",
    f"locations_data.version = {json.dumps(data['version'])}",
    f"locations_data.game = {json.dumps(data['game'])}",
    f"locations_data.total_locations = {data['total_locations']}",
    "",
    "-- Row ID (0..50) to AP Location",
    "locations_data.row_id_to_location = {",
]

for row_id, item in sorted(data["row_id_to_location"].items(), key=lambda x: int(x[0])):
    lines.append(f'    [{int(row_id)}] = {{ id = {item["id"]}, name = {json.dumps(item["name"])} }},')

lines.append("}")
lines.append("")
lines.append("-- Location Name to ID")
lines.append("locations_data.location_name_to_id = {")
for name, loc_id in sorted(data["location_name_to_id"].items()):
    lines.append(f'    [{json.dumps(name)}] = {loc_id},')
lines.append("}")
lines.append("")
lines.append("-- Location ID to Name")
lines.append("locations_data.location_id_to_name = {")
for loc_id, name in sorted(data["location_id_to_name"].items(), key=lambda x: int(x[0])):
    lines.append(f'    [{loc_id}] = {json.dumps(name)},')
lines.append("}")
lines.append("")
lines.append("return locations_data")
lines.append("")

out_lua = Path("ue4ss_mod/FNAFHWArchipelago/Scripts/lib/locations_data.lua")
out_lua.write_text("\n".join(lines), encoding="utf-8")
print(f"Generated {out_lua}!")
